name: Dev Build

on:
  push:
    branches:
      - ver/*

jobs:
  dev-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          java-version: 8

      - uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

      - name: Configure Git
        run: |
          git config --global user.email "no-reply@github.com"
          git config --global user.name "Github Actions"

      - name: Patch Beast
        run: |
          git submodule update --init --recursive
          chmod +x ./beast
          ./beast jar

      - uses: actions/upload-artifact@v4
        with:
          name: Beast-JDK8
          path: ./Beast-Server/target/beast-1.12.2.jar
